spring:
  cloud:
    function:
      definition: sendResetLink          # lie la fonction au binding
    stream:
      defaultBinder: kafka
      kafka:
        binder:
          brokers:
            - ${SPRING_KAFKA:localhost:29092}
      bindings:
        sendResetLink-in-0: # nom = <functionName>-in-0
          destination: password-reset-requested   # topic � �couter
          group: notification-service             # consumer group (obligatoire)
          contentType: application/json
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
  config:
    import: "optional:configserver:http://localhost:8071/"
  profiles:
    active:
      - "prod"
  application:
    name: notification-service


server:
  port: 3004

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  health:
    probes:
      enabled: true
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}



eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/


info:
  app:
    name: "notification-service"
    description: "notification service microservice"

logging:
  file:
    name: ${LOG_FILE_NAME:logs/notification-service.log}
  structured:
    format:
      console: ecs
      file: ecs
    ecs:
      service:
        name: ${spring.application.name}
        environment: ${SPRING_PROFILES_ACTIVE:local}
  level:
    root: INFO
